/**
 * Additional global brand SKUs (Americas / Europe / APAC / more WA options).
 * Merged with the core INVERTERS list at match time.
 */
import type { InverterSpecs, PanelSpecs } from './equipmentDatabase';

export const EXTRA_INVERTERS: InverterSpecs[] = [
  // --- More 12 V / 24 V ---
  {
    brand: 'Victron Energy',
    model: 'EasySolar 12/1600/70 MPPT 100/50',
    sizeKva: 1.6,
    voltageV: 12,
    mpptVocLimit: 100,
    mpptVmpMin: 15,
    mpptVmpMax: 80,
    maxPvCurrent: 50,
    maxPvPower: 700,
    numMppts: 1,
    maxStringsPerMppt: 1,
    efficiency: 0.92,
    maxBatteryChargeCurrentA: 70,
    maxBatteryDischargeCurrentA: 120,
    surgeFactor: 2.0,
    topology: 'off_grid',
    phases: 1,
    regions: ['europe', 'americas']
  },
  {
    brand: 'Victron Energy',
    model: 'EasySolar 24/3000/70 MPPT 150/70',
    sizeKva: 3.0,
    voltageV: 24,
    mpptVocLimit: 150,
    mpptVmpMin: 30,
    mpptVmpMax: 120,
    maxPvCurrent: 70,
    maxPvPower: 2000,
    numMppts: 1,
    maxStringsPerMppt: 2,
    efficiency: 0.94,
    maxBatteryChargeCurrentA: 70,
    maxBatteryDischargeCurrentA: 140,
    surgeFactor: 2.0,
    topology: 'off_grid',
    phases: 1,
    regions: ['europe', 'americas']
  },
  {
    brand: 'Growatt',
    model: 'SPF 5000 ES 5kVA / 48V Off-Grid',
    sizeKva: 5.0,
    voltageV: 48,
    mpptVocLimit: 450,
    mpptVmpMin: 120,
    mpptVmpMax: 430,
    maxPvCurrent: 18,
    maxPvPower: 6000,
    numMppts: 2,
    maxStringsPerMppt: 1,
    efficiency: 0.93,
    maxBatteryChargeCurrentA: 100,
    maxBatteryDischargeCurrentA: 110,
    surgeFactor: 2.0,
    topology: 'off_grid',
    phases: 1,
    regions: ['west_africa', 'asia_pacific']
  },
  {
    brand: 'Sol-Ark',
    model: 'Sol-Ark 5K-2P Hybrid 5kVA',
    sizeKva: 5.0,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 125,
    mpptVmpMax: 425,
    maxPvCurrent: 20,
    maxPvPower: 6500,
    numMppts: 2,
    maxStringsPerMppt: 2,
    efficiency: 0.96,
    maxBatteryChargeCurrentA: 120,
    maxBatteryDischargeCurrentA: 120,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['americas']
  },
  {
    brand: 'Sol-Ark',
    model: 'Sol-Ark 8K Hybrid 8kVA',
    sizeKva: 8.0,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 150,
    mpptVmpMax: 425,
    maxPvCurrent: 26,
    maxPvPower: 11000,
    numMppts: 2,
    maxStringsPerMppt: 2,
    efficiency: 0.96,
    maxBatteryChargeCurrentA: 185,
    maxBatteryDischargeCurrentA: 185,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['americas']
  },
  {
    brand: 'Sol-Ark',
    model: 'Sol-Ark 12K Hybrid 12kVA',
    sizeKva: 12.0,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 150,
    mpptVmpMax: 425,
    maxPvCurrent: 26,
    maxPvPower: 13000,
    numMppts: 2,
    maxStringsPerMppt: 2,
    efficiency: 0.96,
    maxBatteryChargeCurrentA: 275,
    maxBatteryDischargeCurrentA: 275,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['americas']
  },
  {
    brand: 'EG4',
    model: '18kPV Hybrid 12kVA',
    sizeKva: 12.0,
    voltageV: 48,
    mpptVocLimit: 600,
    mpptVmpMin: 120,
    mpptVmpMax: 500,
    maxPvCurrent: 25,
    maxPvPower: 18000,
    numMppts: 3,
    maxStringsPerMppt: 2,
    efficiency: 0.96,
    maxBatteryChargeCurrentA: 250,
    maxBatteryDischargeCurrentA: 250,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['americas']
  },
  {
    brand: 'EG4',
    model: '6000XP Off-Grid 6kVA',
    sizeKva: 6.0,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 120,
    mpptVmpMax: 450,
    maxPvCurrent: 27,
    maxPvPower: 8000,
    numMppts: 2,
    maxStringsPerMppt: 2,
    efficiency: 0.93,
    maxBatteryChargeCurrentA: 140,
    maxBatteryDischargeCurrentA: 140,
    surgeFactor: 2.0,
    topology: 'off_grid',
    phases: 1,
    regions: ['americas']
  },
  {
    brand: 'SMA',
    model: 'Sunny Island 8.0H (with external PV)',
    sizeKva: 6.0,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 120,
    mpptVmpMax: 450,
    maxPvCurrent: 20,
    maxPvPower: 8000,
    numMppts: 1,
    maxStringsPerMppt: 2,
    efficiency: 0.95,
    maxBatteryChargeCurrentA: 140,
    maxBatteryDischargeCurrentA: 165,
    surgeFactor: 1.8,
    topology: 'hybrid',
    phases: 1,
    regions: ['europe']
  },
  {
    brand: 'GoodWe',
    model: 'GW3648D-ES Hybrid 3.6kVA',
    sizeKva: 3.6,
    voltageV: 48,
    mpptVocLimit: 580,
    mpptVmpMin: 125,
    mpptVmpMax: 550,
    maxPvCurrent: 12.5,
    maxPvPower: 4600,
    numMppts: 2,
    maxStringsPerMppt: 1,
    efficiency: 0.97,
    maxBatteryChargeCurrentA: 75,
    maxBatteryDischargeCurrentA: 75,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['europe', 'asia_pacific']
  },
  {
    brand: 'Luxpower',
    model: 'LXP 3.6K Hybrid 3.6kVA',
    sizeKva: 3.6,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 120,
    mpptVmpMax: 430,
    maxPvCurrent: 14,
    maxPvPower: 4680,
    numMppts: 2,
    maxStringsPerMppt: 1,
    efficiency: 0.97,
    maxBatteryChargeCurrentA: 80,
    maxBatteryDischargeCurrentA: 80,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['west_africa', 'asia_pacific', 'europe']
  },
  {
    brand: 'Deye',
    model: 'SUN-3.6K-SG03LP1 Hybrid 3.6kVA',
    sizeKva: 3.6,
    voltageV: 48,
    mpptVocLimit: 500,
    mpptVmpMin: 120,
    mpptVmpMax: 430,
    maxPvCurrent: 13,
    maxPvPower: 4680,
    numMppts: 2,
    maxStringsPerMppt: 1,
    efficiency: 0.97,
    maxBatteryChargeCurrentA: 90,
    maxBatteryDischargeCurrentA: 90,
    surgeFactor: 2.0,
    topology: 'hybrid',
    phases: 1,
    regions: ['west_africa', 'asia_pacific', 'europe', 'americas']
  },
  {
    brand: 'MUST',
    model: 'PV1800 VPM 5kVA / 48V',
    sizeKva: 5.0,
    voltageV: 48,
    mpptVocLimit: 450,
    mpptVmpMin: 120,
    mpptVmpMax: 430,
    maxPvCurrent: 80,
    maxPvPower: 5000,
    numMppts: 1,
    maxStringsPerMppt: 2,
    efficiency: 0.93,
    maxBatteryChargeCurrentA: 80,
    maxBatteryDischargeCurrentA: 110,
    surgeFactor: 2.0,
    topology: 'off_grid',
    phases: 1,
    regions: ['west_africa']
  }
];

export const EXTRA_PANELS: PanelSpecs[] = [
  {
    brand: 'JA Solar',
    model: 'JAM54S30 415W',
    sizeW: 415,
    voc: 37.8,
    vmp: 31.5,
    isc: 14.0,
    imp: 13.18,
    tempCoeffVoc: -0.30,
    maxSeriesFuseA: 25,
    maxSystemVoltageV: 1500
  },
  {
    brand: 'Trina Solar',
    model: 'Vertex S 450W',
    sizeW: 450,
    voc: 41.5,
    vmp: 34.6,
    isc: 13.9,
    imp: 13.01,
    tempCoeffVoc: -0.29,
    maxSeriesFuseA: 25,
    maxSystemVoltageV: 1500
  },
  {
    brand: 'REC',
    model: 'Alpha Pure 400W',
    sizeW: 400,
    voc: 45.0,
    vmp: 37.8,
    isc: 11.3,
    imp: 10.58,
    tempCoeffVoc: -0.26,
    maxSeriesFuseA: 25,
    maxSystemVoltageV: 1500
  },
  {
    brand: 'Qcells',
    model: 'Q.PEAK DUO 380W',
    sizeW: 380,
    voc: 41.0,
    vmp: 34.4,
    isc: 11.6,
    imp: 11.05,
    tempCoeffVoc: -0.27,
    maxSeriesFuseA: 20,
    maxSystemVoltageV: 1500
  }
];
